name = "temp-mail"
main = "src/index.ts"
compatibility_date = "2026-08-01"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = true
binding = "ASSETS"

[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "temp-mail"
database_id = "16fe181e-764c-45cd-b310-80db1184a826"
migrations_dir = "migrations"

[vars]
DOMAIN = "toolviet.net"
SALT_TOKEN = "2128a9f00a7134953373847975819670312638e611a9fb7040cfb476620f7d34"
SALT_IP = "9b5c108947696197dac24a6dfad3ba133f45680af4069abe6d0950524b221890"
